/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as SacolaRouteImport } from './routes/sacola'
import { Route as PoliticaTrocaRouteImport } from './routes/politica-troca'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrupoVipRouteImport } from './routes/grupo-vip'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutenticidadeRouteImport } from './routes/autenticidade'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as ContaEnderecosRouteImport } from './routes/conta.enderecos'
import { Route as ContaDadosRouteImport } from './routes/conta.dados'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminFornecedoresRouteImport } from './routes/_authenticated/admin.fornecedores'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin.pedidos.$id'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin.clientes.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SacolaRoute = SacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaTrocaRoute = PoliticaTrocaRouteImport.update({
  id: '/politica-troca',
  path: '/politica-troca',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupoVipRoute = GrupoVipRouteImport.update({
  id: '/grupo-vip',
  path: '/grupo-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticidadeRoute = AutenticidadeRouteImport.update({
  id: '/autenticidade',
  path: '/autenticidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaEnderecosRoute = ContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaDadosRoute = ContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => ContaRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFornecedoresRoute =
  AuthenticatedAdminFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPedidosRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autenticidade': typeof AutenticidadeRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/grupo-vip': typeof GrupoVipRoute
  '/login': typeof LoginRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-troca': typeof PoliticaTrocaRoute
  '/sacola': typeof SacolaRoute
  '/showroom': typeof ShowroomRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autenticidade': typeof AutenticidadeRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/grupo-vip': typeof GrupoVipRoute
  '/login': typeof LoginRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-troca': typeof PoliticaTrocaRoute
  '/sacola': typeof SacolaRoute
  '/showroom': typeof ShowroomRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/autenticidade': typeof AutenticidadeRoute
  '/blog': typeof BlogRouteWithChildren
  '/busca': typeof BuscaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRouteWithChildren
  '/contato': typeof ContatoRoute
  '/entrega': typeof EntregaRoute
  '/favoritos': typeof FavoritosRoute
  '/grupo-vip': typeof GrupoVipRoute
  '/login': typeof LoginRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-troca': typeof PoliticaTrocaRoute
  '/sacola': typeof SacolaRoute
  '/showroom': typeof ShowroomRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/enderecos': typeof ContaEnderecosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/_authenticated/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autenticidade'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrega'
    | '/favoritos'
    | '/grupo-vip'
    | '/login'
    | '/politica-cookies'
    | '/politica-privacidade'
    | '/politica-troca'
    | '/sacola'
    | '/showroom'
    | '/sobre'
    | '/termos'
    | '/admin'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/admin/clientes'
    | '/admin/fornecedores'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/pedidos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autenticidade'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrega'
    | '/favoritos'
    | '/grupo-vip'
    | '/login'
    | '/politica-cookies'
    | '/politica-privacidade'
    | '/politica-troca'
    | '/sacola'
    | '/showroom'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/admin/clientes'
    | '/admin/fornecedores'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/pedidos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/autenticidade'
    | '/blog'
    | '/busca'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrega'
    | '/favoritos'
    | '/grupo-vip'
    | '/login'
    | '/politica-cookies'
    | '/politica-privacidade'
    | '/politica-troca'
    | '/sacola'
    | '/showroom'
    | '/sobre'
    | '/termos'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/conta/dados'
    | '/conta/enderecos'
    | '/conta/pedidos'
    | '/produto/$slug'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/fornecedores'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/pedidos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AutenticidadeRoute: typeof AutenticidadeRoute
  BlogRoute: typeof BlogRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EntregaRoute: typeof EntregaRoute
  FavoritosRoute: typeof FavoritosRoute
  GrupoVipRoute: typeof GrupoVipRoute
  LoginRoute: typeof LoginRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PoliticaTrocaRoute: typeof PoliticaTrocaRoute
  SacolaRoute: typeof SacolaRoute
  ShowroomRoute: typeof ShowroomRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sacola': {
      id: '/sacola'
      path: '/sacola'
      fullPath: '/sacola'
      preLoaderRoute: typeof SacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-troca': {
      id: '/politica-troca'
      path: '/politica-troca'
      fullPath: '/politica-troca'
      preLoaderRoute: typeof PoliticaTrocaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupo-vip': {
      id: '/grupo-vip'
      path: '/grupo-vip'
      fullPath: '/grupo-vip'
      preLoaderRoute: typeof GrupoVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autenticidade': {
      id: '/autenticidade'
      path: '/autenticidade'
      fullPath: '/autenticidade'
      preLoaderRoute: typeof AutenticidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/enderecos': {
      id: '/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof ContaEnderecosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/dados': {
      id: '/conta/dados'
      path: '/dados'
      fullPath: '/conta/dados'
      preLoaderRoute: typeof ContaDadosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fornecedores': {
      id: '/_authenticated/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminPedidosRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientesRoute
    }
  }
}

interface AuthenticatedAdminClientesRouteChildren {
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
}

const AuthenticatedAdminClientesRouteChildren: AuthenticatedAdminClientesRouteChildren =
  {
    AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
  }

const AuthenticatedAdminClientesRouteWithChildren =
  AuthenticatedAdminClientesRoute._addFileChildren(
    AuthenticatedAdminClientesRouteChildren,
  )

interface AuthenticatedAdminPedidosRouteChildren {
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
}

const AuthenticatedAdminPedidosRouteChildren: AuthenticatedAdminPedidosRouteChildren =
  {
    AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  }

const AuthenticatedAdminPedidosRouteWithChildren =
  AuthenticatedAdminPedidosRoute._addFileChildren(
    AuthenticatedAdminPedidosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRouteWithChildren
  AuthenticatedAdminFornecedoresRoute: typeof AuthenticatedAdminFornecedoresRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRouteWithChildren
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRouteWithChildren,
  AuthenticatedAdminFornecedoresRoute: AuthenticatedAdminFornecedoresRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRouteWithChildren,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ContaRouteChildren {
  ContaDadosRoute: typeof ContaDadosRoute
  ContaEnderecosRoute: typeof ContaEnderecosRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaDadosRoute: ContaDadosRoute,
  ContaEnderecosRoute: ContaEnderecosRoute,
  ContaPedidosRoute: ContaPedidosRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AutenticidadeRoute: AutenticidadeRoute,
  BlogRoute: BlogRouteWithChildren,
  BuscaRoute: BuscaRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EntregaRoute: EntregaRoute,
  FavoritosRoute: FavoritosRoute,
  GrupoVipRoute: GrupoVipRoute,
  LoginRoute: LoginRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PoliticaTrocaRoute: PoliticaTrocaRoute,
  SacolaRoute: SacolaRoute,
  ShowroomRoute: ShowroomRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
